default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  host: <%= ENV["DB_HOST"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: <%= ENV["DB_PORT"] %>

development:
  <<: *default
  database: RailsReact_development

test:
  <<: *default
  database: RailsReact_test

production:
  <<: *default
  database: RailsReact_production
  username: RailsReact
  password: <%= ENV["RAILSREACT_DATABASE_PASSWORD"] %>
